services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api/app:/code/app
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
