spec:
  source:
    repoURL: https://github.com/will-wright-eng/argocd-do-test.git
    targetRevision: HEAD
environment: dev
monitoring:
  enabled: true
  namespace: monitoring
api:
  enabled: true
  namespace: demo
  replicas: 2
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
---
