apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - patches/api-deployment.yaml

images:
  - name: api
    newName: registry.digitalocean.com/demo-argocd-registry/demo-api
    newTag: latest
