apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
patchesStrategicMerge:
  - patches/api-deployment.yaml
images:
  - name: api
    newName: your-registry/api
    newTag: dev
